// +build !ignore_autogenerated

/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	application "github.com/kubernetes-sigs/apps_application/pkg/apis/application"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_Application_To_application_Application,
		Convert_application_Application_To_v1alpha1_Application,
		Convert_v1alpha1_ApplicationList_To_application_ApplicationList,
		Convert_application_ApplicationList_To_v1alpha1_ApplicationList,
		Convert_v1alpha1_ApplicationSpec_To_application_ApplicationSpec,
		Convert_application_ApplicationSpec_To_v1alpha1_ApplicationSpec,
		Convert_v1alpha1_ApplicationStatus_To_application_ApplicationStatus,
		Convert_application_ApplicationStatus_To_v1alpha1_ApplicationStatus,
		Convert_v1alpha1_ApplicationStatusStrategy_To_application_ApplicationStatusStrategy,
		Convert_application_ApplicationStatusStrategy_To_v1alpha1_ApplicationStatusStrategy,
		Convert_v1alpha1_ApplicationStrategy_To_application_ApplicationStrategy,
		Convert_application_ApplicationStrategy_To_v1alpha1_ApplicationStrategy,
	)
}

func autoConvert_v1alpha1_Application_To_application_Application(in *Application, out *application.Application, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ApplicationSpec_To_application_ApplicationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ApplicationStatus_To_application_ApplicationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Application_To_application_Application is an autogenerated conversion function.
func Convert_v1alpha1_Application_To_application_Application(in *Application, out *application.Application, s conversion.Scope) error {
	return autoConvert_v1alpha1_Application_To_application_Application(in, out, s)
}

func autoConvert_application_Application_To_v1alpha1_Application(in *application.Application, out *Application, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_application_ApplicationSpec_To_v1alpha1_ApplicationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_application_ApplicationStatus_To_v1alpha1_ApplicationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_application_Application_To_v1alpha1_Application is an autogenerated conversion function.
func Convert_application_Application_To_v1alpha1_Application(in *application.Application, out *Application, s conversion.Scope) error {
	return autoConvert_application_Application_To_v1alpha1_Application(in, out, s)
}

func autoConvert_v1alpha1_ApplicationList_To_application_ApplicationList(in *ApplicationList, out *application.ApplicationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]application.Application)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ApplicationList_To_application_ApplicationList is an autogenerated conversion function.
func Convert_v1alpha1_ApplicationList_To_application_ApplicationList(in *ApplicationList, out *application.ApplicationList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ApplicationList_To_application_ApplicationList(in, out, s)
}

func autoConvert_application_ApplicationList_To_v1alpha1_ApplicationList(in *application.ApplicationList, out *ApplicationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Application)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_application_ApplicationList_To_v1alpha1_ApplicationList is an autogenerated conversion function.
func Convert_application_ApplicationList_To_v1alpha1_ApplicationList(in *application.ApplicationList, out *ApplicationList, s conversion.Scope) error {
	return autoConvert_application_ApplicationList_To_v1alpha1_ApplicationList(in, out, s)
}

func autoConvert_v1alpha1_ApplicationSpec_To_application_ApplicationSpec(in *ApplicationSpec, out *application.ApplicationSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.ComponentGroupKinds = *(*[]v1.GroupKind)(unsafe.Pointer(&in.ComponentGroupKinds))
	out.Selector = (*v1.LabelSelector)(unsafe.Pointer(in.Selector))
	out.Version = in.Version
	out.Description = in.Description
	out.Maintainers = *(*[]string)(unsafe.Pointer(&in.Maintainers))
	out.Owners = *(*[]string)(unsafe.Pointer(&in.Owners))
	out.Keywords = *(*[]string)(unsafe.Pointer(&in.Keywords))
	out.Info = *(*map[string]string)(unsafe.Pointer(&in.Info))
	out.Links = *(*map[string]string)(unsafe.Pointer(&in.Links))
	return nil
}

// Convert_v1alpha1_ApplicationSpec_To_application_ApplicationSpec is an autogenerated conversion function.
func Convert_v1alpha1_ApplicationSpec_To_application_ApplicationSpec(in *ApplicationSpec, out *application.ApplicationSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ApplicationSpec_To_application_ApplicationSpec(in, out, s)
}

func autoConvert_application_ApplicationSpec_To_v1alpha1_ApplicationSpec(in *application.ApplicationSpec, out *ApplicationSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.ComponentGroupKinds = *(*[]v1.GroupKind)(unsafe.Pointer(&in.ComponentGroupKinds))
	out.Selector = (*v1.LabelSelector)(unsafe.Pointer(in.Selector))
	out.Version = in.Version
	out.Description = in.Description
	out.Maintainers = *(*[]string)(unsafe.Pointer(&in.Maintainers))
	out.Owners = *(*[]string)(unsafe.Pointer(&in.Owners))
	out.Keywords = *(*[]string)(unsafe.Pointer(&in.Keywords))
	out.Info = *(*map[string]string)(unsafe.Pointer(&in.Info))
	out.Links = *(*map[string]string)(unsafe.Pointer(&in.Links))
	return nil
}

// Convert_application_ApplicationSpec_To_v1alpha1_ApplicationSpec is an autogenerated conversion function.
func Convert_application_ApplicationSpec_To_v1alpha1_ApplicationSpec(in *application.ApplicationSpec, out *ApplicationSpec, s conversion.Scope) error {
	return autoConvert_application_ApplicationSpec_To_v1alpha1_ApplicationSpec(in, out, s)
}

func autoConvert_v1alpha1_ApplicationStatus_To_application_ApplicationStatus(in *ApplicationStatus, out *application.ApplicationStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	return nil
}

// Convert_v1alpha1_ApplicationStatus_To_application_ApplicationStatus is an autogenerated conversion function.
func Convert_v1alpha1_ApplicationStatus_To_application_ApplicationStatus(in *ApplicationStatus, out *application.ApplicationStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ApplicationStatus_To_application_ApplicationStatus(in, out, s)
}

func autoConvert_application_ApplicationStatus_To_v1alpha1_ApplicationStatus(in *application.ApplicationStatus, out *ApplicationStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	return nil
}

// Convert_application_ApplicationStatus_To_v1alpha1_ApplicationStatus is an autogenerated conversion function.
func Convert_application_ApplicationStatus_To_v1alpha1_ApplicationStatus(in *application.ApplicationStatus, out *ApplicationStatus, s conversion.Scope) error {
	return autoConvert_application_ApplicationStatus_To_v1alpha1_ApplicationStatus(in, out, s)
}

func autoConvert_v1alpha1_ApplicationStatusStrategy_To_application_ApplicationStatusStrategy(in *ApplicationStatusStrategy, out *application.ApplicationStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_ApplicationStatusStrategy_To_application_ApplicationStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_ApplicationStatusStrategy_To_application_ApplicationStatusStrategy(in *ApplicationStatusStrategy, out *application.ApplicationStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_ApplicationStatusStrategy_To_application_ApplicationStatusStrategy(in, out, s)
}

func autoConvert_application_ApplicationStatusStrategy_To_v1alpha1_ApplicationStatusStrategy(in *application.ApplicationStatusStrategy, out *ApplicationStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_application_ApplicationStatusStrategy_To_v1alpha1_ApplicationStatusStrategy is an autogenerated conversion function.
func Convert_application_ApplicationStatusStrategy_To_v1alpha1_ApplicationStatusStrategy(in *application.ApplicationStatusStrategy, out *ApplicationStatusStrategy, s conversion.Scope) error {
	return autoConvert_application_ApplicationStatusStrategy_To_v1alpha1_ApplicationStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_ApplicationStrategy_To_application_ApplicationStrategy(in *ApplicationStrategy, out *application.ApplicationStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_ApplicationStrategy_To_application_ApplicationStrategy is an autogenerated conversion function.
func Convert_v1alpha1_ApplicationStrategy_To_application_ApplicationStrategy(in *ApplicationStrategy, out *application.ApplicationStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_ApplicationStrategy_To_application_ApplicationStrategy(in, out, s)
}

func autoConvert_application_ApplicationStrategy_To_v1alpha1_ApplicationStrategy(in *application.ApplicationStrategy, out *ApplicationStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_application_ApplicationStrategy_To_v1alpha1_ApplicationStrategy is an autogenerated conversion function.
func Convert_application_ApplicationStrategy_To_v1alpha1_ApplicationStrategy(in *application.ApplicationStrategy, out *ApplicationStrategy, s conversion.Scope) error {
	return autoConvert_application_ApplicationStrategy_To_v1alpha1_ApplicationStrategy(in, out, s)
}
