/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package v1alpha1

import (
	"github.com/kubernetes-sigs/apps_application/pkg/apis/application"
	"github.com/najena/kubebuilder/pkg/builders"
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

var (
	// Define CRDs for resources
	ApplicationCRD = v1beta1.CustomResourceDefinition{
		ObjectMeta: metav1.ObjectMeta{
			Name: "applications.application.k8s.io",
		},
		Spec: v1beta1.CustomResourceDefinitionSpec{
			Group:   "application.k8s.io",
			Version: "v1alpha1",
			Names: v1beta1.CustomResourceDefinitionNames{
				Kind:   "Application",
				Plural: "applications",
			},
			Scope: "Namespaced",
		},
	}
	// Collect CRDs in this group version
	CRDs = []v1beta1.CustomResourceDefinition{
		ApplicationCRD,
	}

	// Register APIs
	applicationApplicationStorage = builders.NewApiResource( // Resource status endpoint
		application.InternalApplication,
		ApplicationSchemeFns{},
		func() runtime.Object { return &Application{} },     // Register versioned resource
		func() runtime.Object { return &ApplicationList{} }, // Register versioned resource list
		&ApplicationStrategy{builders.StorageStrategySingleton},
	)
	ApiVersion = builders.NewApiVersion("application.k8s.io", "v1alpha1").WithResources(
		applicationApplicationStorage,
		builders.NewApiResource( // Resource status endpoint
			application.InternalApplicationStatus,
			ApplicationSchemeFns{},
			func() runtime.Object { return &Application{} },     // Register versioned resource
			func() runtime.Object { return &ApplicationList{} }, // Register versioned resource list
			&ApplicationStatusStrategy{builders.StatusStorageStrategySingleton},
		))

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

//
// Application Functions and Structs
//
// +k8s:deepcopy-gen=false
type ApplicationSchemeFns struct {
	builders.DefaultSchemeFns
}

// +k8s:deepcopy-gen=false
type ApplicationStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type ApplicationStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type ApplicationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Application `json:"items"`
}
