/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package application

import (
	"fmt"
	"github.com/najena/kubebuilder/pkg/builders"
	"k8s.io/apimachinery/pkg/apis/meta/internalversion"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apiserver/pkg/endpoints/request"
	"k8s.io/apiserver/pkg/registry/rest"
)

var (
	InternalApplication = builders.NewInternalResource(
		"applications",
		"Application",
		func() runtime.Object { return &Application{} },
		func() runtime.Object { return &ApplicationList{} },
	)
	InternalApplicationStatus = builders.NewInternalResourceStatus(
		"applications",
		"ApplicationStatus",
		func() runtime.Object { return &Application{} },
		func() runtime.Object { return &ApplicationList{} },
	)
	// Registered resources and subresources
	ApiVersion = builders.NewApiGroup("application.k8s.io").WithKinds(
		InternalApplication,
		InternalApplicationStatus,
	)

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type Application struct {
	metav1.TypeMeta
	metav1.ObjectMeta
	Spec   ApplicationSpec
	Status ApplicationStatus
}

type ApplicationSpec struct {
	Type                string
	ComponentGroupKinds []metav1.GroupKind
	Selector            *metav1.LabelSelector
	Version             string
	Description         string
	Maintainers         []string
	Owners              []string
	Keywords            []string
	Info                map[string]string
	Links               map[string]string
}

type ApplicationStatus struct {
	ObservedGeneration int64
}

//
// Application Functions and Structs
//
// +k8s:deepcopy-gen=false
type ApplicationStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type ApplicationStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type ApplicationList struct {
	metav1.TypeMeta
	metav1.ListMeta
	Items []Application
}

func (Application) NewStatus() interface{} {
	return ApplicationStatus{}
}

func (pc *Application) GetStatus() interface{} {
	return pc.Status
}

func (pc *Application) SetStatus(s interface{}) {
	pc.Status = s.(ApplicationStatus)
}

func (pc *Application) GetSpec() interface{} {
	return pc.Spec
}

func (pc *Application) SetSpec(s interface{}) {
	pc.Spec = s.(ApplicationSpec)
}

func (pc *Application) GetObjectMeta() *metav1.ObjectMeta {
	return &pc.ObjectMeta
}

func (pc *Application) SetGeneration(generation int64) {
	pc.ObjectMeta.Generation = generation
}

func (pc Application) GetGeneration() int64 {
	return pc.ObjectMeta.Generation
}

// Registry is an interface for things that know how to store Application.
// +k8s:deepcopy-gen=false
type ApplicationRegistry interface {
	ListApplications(ctx request.Context, options *internalversion.ListOptions) (*ApplicationList, error)
	GetApplication(ctx request.Context, id string, options *metav1.GetOptions) (*Application, error)
	CreateApplication(ctx request.Context, id *Application) (*Application, error)
	UpdateApplication(ctx request.Context, id *Application) (*Application, error)
	DeleteApplication(ctx request.Context, id string) (bool, error)
}

// NewRegistry returns a new Registry interface for the given Storage. Any mismatched types will panic.
func NewApplicationRegistry(sp builders.StandardStorageProvider) ApplicationRegistry {
	return &storageApplication{sp}
}

// Implement Registry
// storage puts strong typing around storage calls
// +k8s:deepcopy-gen=false
type storageApplication struct {
	builders.StandardStorageProvider
}

func (s *storageApplication) ListApplications(ctx request.Context, options *internalversion.ListOptions) (*ApplicationList, error) {
	if options != nil && options.FieldSelector != nil && !options.FieldSelector.Empty() {
		return nil, fmt.Errorf("field selector not supported yet")
	}
	st := s.GetStandardStorage()
	obj, err := st.List(ctx, options)
	if err != nil {
		return nil, err
	}
	return obj.(*ApplicationList), err
}

func (s *storageApplication) GetApplication(ctx request.Context, id string, options *metav1.GetOptions) (*Application, error) {
	st := s.GetStandardStorage()
	obj, err := st.Get(ctx, id, options)
	if err != nil {
		return nil, err
	}
	return obj.(*Application), nil
}

func (s *storageApplication) CreateApplication(ctx request.Context, object *Application) (*Application, error) {
	st := s.GetStandardStorage()
	obj, err := st.Create(ctx, object, nil, true)
	if err != nil {
		return nil, err
	}
	return obj.(*Application), nil
}

func (s *storageApplication) UpdateApplication(ctx request.Context, object *Application) (*Application, error) {
	st := s.GetStandardStorage()
	obj, _, err := st.Update(ctx, object.Name, rest.DefaultUpdatedObjectInfo(object), nil, nil)
	if err != nil {
		return nil, err
	}
	return obj.(*Application), nil
}

func (s *storageApplication) DeleteApplication(ctx request.Context, id string) (bool, error) {
	st := s.GetStandardStorage()
	_, sync, err := st.Delete(ctx, id, nil)
	return sync, err
}
