# Copyright 2020 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "withcrd"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "withcrd-ok"
  componentGVKs:
  - group: apps
    version: v1
    kind: Deployment
  - group: batch
    version: v1
    kind: Job
  - group: ""
    version: v1
    kind: Service
  - group: ""
    version: v1
    kind: ConfigMap
  - group: test.crd.com
    version: v1
    kind: TestCRD
  addOwnerRef: true
  descriptor:
    type: "test"
    keywords:
    - "test"
    version: "0.0.1"
    description: "It is a simple E2E test app"
    maintainers:
    - name: Test Dev
      email: dev@test.org
    owners:
    - name: Test Admin
      email: admin@test.org
