apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  labels:
    api: default
    platform: kubernetes_sigs_kubebuilder
  name: default-system
spec: {}
status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    api: default
    platform: kubernetes_sigs_kubebuilder
  name: default-role
rules:
- apiGroups:
  - app.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    api: default
    platform: kubernetes_sigs_kubebuilder
  name: default-rolebinding
  namespace: default-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default-system
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: default
    platform: kubernetes_sigs_kubebuilder
  name: applications.app.k8s.io
spec:
  group: app.k8s.io
  names:
    kind: Application
    plural: applications
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            componentKinds:
              items:
                properties:
                  group:
                    type: string
                  kind:
                    type: string
                type: object
              type: array
            description:
              type: string
            assemblyPhase:
              type: string
              enum:
              - Pending
              - Succeeded
              - Failed
            info:
              items:
                properties:
                  name:
                    type: string
                  value:
                    type: string
                type: object
              type: array
            keywords:
              items:
                type: string
              type: array
            links:
              items:
                properties:
                  description:
                    type: string
                  url:
                    type: string
                type: object
              type: array
            maintainers:
              items:
                properties:
                  email:
                    type: string
                  name:
                    type: string
                  url:
                    type: string
                type: object
              type: array
            notes:
              type: string
            owners:
              items:
                type: string
              type: array
            selector:
              properties:
                matchExpressions:
                  items:
                    properties:
                      key:
                        type: string
                      operator:
                        type: string
                      values:
                        items:
                          type: string
                        type: array
                    type: object
                  type: array
                matchLabels:
                  type: object
              type: object
            type:
              type: string
            version:
              type: string
          type: object
        status:
          properties:
            observedGeneration:
              type: int64
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    api: default
    control-plane: controller-manager
    platform: kubernetes_sigs_kubebuilder
  name: default-controller-manager-service
  namespace: default-system
spec:
  clusterIP: None
  selector:
    api: default
    control-plane: controller-manager
    platform: kubernetes_sigs_kubebuilder
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    api: default
    control-plane: controller-manager
    platform: kubernetes_sigs_kubebuilder
  name: default-controller-manager
  namespace: default-system
spec:
  replicas: 1
  selector:
    matchLabels:
      api: default
      control-plane: controller-manager
      platform: kubernetes_sigs_kubebuilder
  serviceName: default-controller-manager-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        api: default
        control-plane: controller-manager
        platform: kubernetes_sigs_kubebuilder
    spec:
      containers:
      - args:
        - --install-crds=false
        command:
        - /root/controller-manager
        image: my-image
        name: controller-manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
  updateStrategy: {}
status:
  replicas: 0
requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
  updateStrategy: {}
status:
  replicas: 0
