# Copyright 2020 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "wordpress-01"
  labels:
    app.kubernetes.io/name: "wordpress-01"
    app.kubernetes.io/version: "3"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "wordpress-01"
  componentKinds:
  - group: v1
    kind: Service
  - group: apps
    kind: Deployment
  - group: apps
    kind: StatefulSet
  descriptor:
    type: "wordpress"
    version: "4.9.4"
    description: "WordPress is open source software you can use to create a beautiful website, blog, or app."
    icons:
    - src: "https://example.com/wordpress.png"
      type: "image/png"
    assemblyPhase: "Pending"
    maintainers:
    - name: Wordpress Dev
      email: dev@wordpress.org
    owners:
    - name: Wordpress Admin
      email: admin@wordpress.org
    keywords:
    - "cms"
    - "blog"
    - "wordpress"
    links:
    - description: About
      url: "https://wordpress.org/"
    - description: Web Server Dashboard
      url: "https://metrics/internal/wordpress-01/web-app"
    - description: Mysql Dashboard
      url: "https://metrics/internal/wordpress-01/mysql"
