# Copyright 2020 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "wordpress-01"
  labels:
    app.kubernetes.io/name: "wordpress-01"
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: "wordpress-01"
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: StatefulSet
  addOwnerRef: true
  descriptor:
    type: "wordpress"
    keywords:
      - "cms"
      - "blog"
      - "wordpress"
    links:
      - description: About
        url: "https://wordpress.org/"
      - description: Web Server Dashboard
        url: "https://metrics/internal/wordpress-01/web-app"
      - description: Mysql Dashboard
        url: "https://metrics/internal/wordpress-01/mysql"
    version: "4.9.4"
    description: "WordPress is open source software you can use to create a beautiful website, blog, or app."
    icons:
      - src: "https://s.w.org/style/images/about/WordPress-logotype-wmark.png"
        type: "image/png"
        size: "1000x1000"
      - src: "https://s.w.org/style/images/about/WordPress-logotype-standard.png"
        type: "image/png"
        size: "2000x680"
    maintainers:
      - name: Wordpress Dev
        email: dev@wordpress.org
    owners:
      - name: Wordpress Admin
        email: admin@wordpress.org
